### PR TITLE
Feature/begin translations

### LINKED ISSUE #33: Begin translation

### PR DESCRIPTION
**Pull request by raujonas**
#33

### CODE REVIEW

**Comment by raujonas** [comment]
Hi @G-dH. I began with the translations based on the recent prefs optimization and the [tutorial](https://gjs.guide/extensions/development/translations.html#preparing-an-extension) you mentioned. However I cannot get it to work at all. This is why I wanted to ask you if you can spot an obvious error in my implementation, since I've seen that you already have translations successfully implemented in your extension too :blush:

**Comment by G-dH** [comment]
Hi,
uuid != gettext-domain
`const Gettext = imports.gettext.domain(Me.metadata.gettext-domain);`
if you add the `gettext-domain` to your `metadata.json` file.
Or directly:
`const Gettext = imports.gettext.domain('executor');`
Translation file name has to match the gettext-domain name.
`local/de/LC_MESSAGES/executor.mo`

**Comment by raujonas** [comment]
Thanks! In the end the wrong filename of `local/de/LC_MESSAGES/executor.mo` was the issue I guess, now it's working as expected :100:

**Comment by G-dH** [comment]
Yes, the .mo file name must match the gettext-domain name, that was the problem. You can obviously use the uuid for domain name, I just wasn't sure about allowed chars.

**Pull request merged**
